### ISSUE TITLE
Pls fix it the player is not playing!

### ISSUE THREAD

**Issue by vizzy-play** [nareshban1/animesenpair#2]

**Comment by nareshban1** [comment]
I will fix it at the end of this week. Been busy with work. I was noob at redux when i started this so the player and episode list has issues.

**Comment by nareshban1** [comment]
Yeah i know i have been planning to fix the issue but was busy with work
will fix it soon. Thanks for the reminder though.

**Comment by nareshban1** [comment]
There seems to issue with the new updates in the ani api episode links. We have to start implementing our own proxy to fetch the episodes and the episode are also not loading cause its too slow. Other than that I have updated a lot of code. Implemented RTK Query rather than RTK. I am also fixed the issue with the episode list fetch and some issues with too many api requests. I will test and update it in the future.
